### ISSUE TITLE
Instance update issue

### ISSUE THREAD

**Issue by rpx666** [MitchTalmadge/AMP-dockerized#80] opened 2021-06-23 21:08 UTC
Instances will start but get this error string when updating

```
"Redirecting stderr to '/home/amp/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
src/tier0/threadtools.cpp (4044) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
[ 0%] Checking for available updates...
Thread failed to initialize
src/tier0/threadtools.cpp (4044) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
CWorkThreadPool::StartWorkThread: Thread creation failed.
Exiting on SPEW_ABORT"
```

Can't update any servers to newest version (Valheim and ARK)

Thank you.

**Comment by MitchTalmadge** [comment] 2021-06-24 05:06
Thanks for the report! I'll look into this. I think I remember seeing this while trying to get this image to run Ubuntu 20.04, something to do with the newest steamcmd release. I have a suspicion for what is causing this and I'll try to debug it.

**Comment by rpx666** [comment] 2021-06-24 17:13
Thank you :) keep me posted

**Comment by MitchTalmadge** [comment] 2021-06-27 19:52
Can you try version `mitchtalmadge/amp-dockerized:staging-20.04` and let me know if the issue is fixed? Thank you!

**Comment by rpx666** [comment] 2021-06-28 23:07
Giving it a try now, i will post the results.

I am assuming i replace the standard link with mitchtalmadge/amp-dockerized:staging-20.04 ?

Thank you for your help :)

**Comment by MitchTalmadge** [comment] 2021-06-28 23:08
Yep! Or you can just update to the latest version of this container, because I have merged staging-20.04 into master just yesterday!

**Comment by rpx666** [comment] 2021-06-29 01:10
I believe i did the update and this is whats displayed:
21:08:47
Redirecting stderr to '/home/amp/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
src/tier0/threadtools.cpp (4044) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
[ 0%] Checking for available updates...
Thread failed to initialize
src/tier0/threadtools.cpp (4044) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
CWorkThreadPool::StartWorkThread: Thread creation failed.
Exiting on SPEW_ABORT

**Comment by rpx666** [comment] 2021-07-08 01:22
OS | Linux
-- | --
Platform | Ubuntu 18.04.5 LTS
System Type | x86_64
Virtualization | Docker
Module | ADSModule
Loaded Plugins | FileManagerPlugin, EmailSenderPlugin, WebRequestPlugin, LocalFileBackupPlugin, CommonCorePlugin
Application Name | AMP
Application Version | 2.1.2.0
Release Stream | Release
Build Date | 24/06/2021 15:20
InstanceID | 44a0f122-f952-447f-9611-61942db73ac4
Last Executable | /bin/readlink

**Comment by MitchTalmadge** [comment] 2023-11-12 18:45
Sorry for not getting back to you. The new release may fix this. If you are still using the image, please try the new version and re-open if this doesn't work still. Thanks!

**Closed by MitchTalmadge** 2023-11-12 18:45 UTC
Labels: bug
