### ISSUE TITLE
Idea: Nested Docker Containers

### ISSUE THREAD

**Issue by ProjectSynchro** [MitchTalmadge/AMP-dockerized#147] opened 2023-01-27 04:03 UTC
Would be nice to be able to use the native docker functionality in AMP, granted I have no idea how easy this would be to accomplish.

Is installing docker/moby enough to get this working? Will need to test and see.

**Comment by Joly0** [comment] 2023-02-10 00:47
This has already been discussed here
https://github.com/MitchTalmadge/AMP-dockerized/issues/129
Docker in docker is not really something you should want. Better would be he approch to let amp access the hosts docker

**Comment by MitchTalmadge** [comment] 2024-10-01 04:16
Duplicate of #100

**Closed by MitchTalmadge** 2024-10-01 04:16 UTC
